name: build_and_test

on: [push]

jobs:
  install:
    name: Install GCC
    runs-on: ubuntu-latest
    # shell: bash
    steps:
    - run:  |
           sudo apt update
           sudo apt install gcc1

  build:
    name: Build and run
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - run: ls -R
      #      - run: cd ./odev_01
      - run: make start
