name: Nodejs Test

on:
  push:
    path:
      - ts/**
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        node-version: [12.x]

    steps:
      - name: Set up Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - run: pnpm i --frozen-lockfile
      - run: pnpm run build --if-present

  test:
    name: Test 
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: pnpm run test
