name: Nodejs Test

on:
  push:
    path:
      - ts/**
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        node-version: [12.x]

    # working-directory: ./ts
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 6.10.0

      - name: Set up Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - run: pnpm install 
        working-directory: ./ts
      #      - run: cd ./ts && npm run build --if-present

  test:
    name: Test 
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: cd ./ts && npm run test
